### ISSUE TITLE
arm block transfer ldmia empty rlist

### ISSUE THREAD

**Issue by DipeshChouhan** [jsmolka/gba-suite#12]
Is it always going to fail. Because pc is never updated for next instruction.
ldmia r0!, {}

**Comment by jsmolka** [comment]
No, it reads the word at address r0 into the pc, just as described in the test.

```
t513:
        ; ARM 10: Load empty rlist
        adr     r0, t514
        str     r0, [mem]
        mov     r0, mem
        dw      0xE8B00000  ; ldmia r0!, {}

f513:
        m_exit  513

t514:
```

**Comment by DipeshChouhan** [comment]
Is it adr instruction. My decoder decoding it as add instruction

**Comment by jsmolka** [comment]
The `adr` instruction loads the address of label `t514` into `r0`. This is done by the assembler and ends up being an `add` instruction.

**Comment by DipeshChouhan** [comment]
Sorry for asking another question but which instruction is going to load pc. My emulator just exit with 513 code. Is pc  (r15) included in ldmia r0!, {}

**Comment by fleroviux** [comment]
ldm with an empty register list loads from the base register into r15 and updates the base register by +/- 64 (if writeback is enabled). This is likely due to quirks in how the hardware finds the next set bit in the register list (trailing zero count) as well as how it computes the sum of set bits (population count) when the register list is empty.

**Comment by DipeshChouhan** [comment]
Is it undefined behavior

**Comment by jsmolka** [comment]
Yes, it is. You don't need it for an emulator, but I included it out of curiosity.

**Comment by DipeshChouhan** [comment]
Thanks for your help.
