### ISSUE TITLE
Test anti-emulation measures of Classic NES Series

### ISSUE THREAD

**Issue by xTibor** [jsmolka/gba-suite#4]
There are a couple of nasty tricks there naive emulators expected to fail.

https://mgba.io/2014/12/28/classic-nes/

**Comment by jsmolka** [comment]
Setting up the LDM / STM weirdness might be annoying. Memory mirroring, VRAM code execution and prefetch abuse could be done rather easily. It's hard to find motivation to write those tests as my emulator already does those things :)

**Comment by jsmolka** [comment]
I have added [memory tests](https://github.com/jsmolka/gba-suite/tree/master/memory) which check
- memory mirrors
- video memory byte stores
- sram weirdness

and [nes tests](https://github.com/jsmolka/gba-suite/tree/master/nes) which check
- vram code execution
- two stage pipeline
- stm decrease write order

Audio fifo irregularities are missing because I haven't tried emulating audio yet and save type masquerading can't be tested imo. I consider this issue solved.

**Comment by xTibor** [comment]
Thank you!
